### ISSUE TITLE
Support  integrating Ollama as a model provider

### ISSUE THREAD

**Issue by benlyazid** [confident-ai/deepeval#1007]
Hi, 
Is there a way to  use Ollama as an lLlm provider

**Comment by hearwish** [comment]
--terminal
deepeval set-local-model --model-name=llama3:8b --base-url="http://localhost:11434/v1/" --api-key="ollama"

**Comment by fabiannagel** [comment]
Is there any way to do this programatically from Python?

**Comment by SuperHao-Wu** [comment]
> Is there any way to do this programatically from Python?

after you set it to use local model : 
```shell
deepeval set-local-model --model-name=llama3.1:8b \
    --base-url="http://localhost:11434/v1/" \
    --api-key="ollama"
```
you can call relevant function without specifying the model, it will automatically use the local model when need LLM 
```python
metric = SummarizationMetric(
    threshold=0.5,
    assessment_questions=[
        "Is the coverage score based on a percentage of 'yes' answers?",
        "Does the score ensure the summary's accuracy with the source?",
        "Does a higher score mean a more comprehensive summary?",
    ],
    include_reason=True,
    
)
```

**Comment by 21m1n** [comment]
this is how i run ollama local models:

```python 
from deepeval.models.gpt_model import CustomChatOpenAI

model_local = CustomChatOpenAI(
                model_name="llama3",
                openai_api_key="ollama",
                base_url="http://localhost:11434/v1/",
                # format=json to enable Ollama JSON mode
                temperature=0,
            )

evaluator = DeepEvalFaithfulnessEvaluator(
    model=model_local
)
```

**Comment by VasilisPoulos** [comment]
> this is how i run ollama local models:
> 
> ```python
> from deepeval.models.gpt_model import CustomChatOpenAI
> 
> model_local = CustomChatOpenAI(
>                 model_name="llama3",
>                 openai_api_key="ollama",
>                 base_url="http://localhost:11434/v1/",
>                 # format=json to enable Ollama JSON mode
>                 temperature=0,
>             )
> 
> evaluator = DeepEvalFaithfulnessEvaluator(
>     model=model_local
> )
> ```

Do you also use this with synthesizer.generate* functions? If so, an example would be appreciated!

**Comment by 21m1n** [comment]
> > this is how i run ollama local models:
> > ```python
> > from deepeval.models.gpt_model import CustomChatOpenAI
> > 
> > model_local = CustomChatOpenAI(
> >                 model_name="llama3",
> >                 openai_api_key="ollama",
> >                 base_url="http://localhost:11434/v1/",
> >                 # format=json to enable Ollama JSON mode
> >                 temperature=0,
> >             )
> > 
> > evaluator = DeepEvalFaithfulnessEvaluator(
> >     model=model_local
> > )
> > ```
> 
> Do you also use this with synthesizer.generate* functions? If so, an example would be appreciated!

i edited my original answer. 

i found a workaround by adding `def __class__(self)` at the end, now I'm able to use it as `synthesizer` now, it's working in the following example: 

```python

from deepeval.synthesizer import Synthesizer

model_local = OllamaLLM(model_name=model_name)

synthesizer1= Synthesizer(model=model_local)
synthesizer.generate_goldens_from_contexts(
    contexts=[
        ["The Earth revolves around the Sun.", "Planets are celestial bodies."],
        ["Water freezes at 0 degrees Celsius.", "The chemical formula for water is H2O."],
    ]
)
```

**Comment by VasilisPoulos** [comment]
> > > this is how i run ollama local models:
> > > ```python
> > > from deepeval.models.gpt_model import CustomChatOpenAI
> > > 
> > > model_local = CustomChatOpenAI(
> > >                 model_name="llama3",
> > >                 openai_api_key="ollama",
> > >                 base_url="http://localhost:11434/v1/",
> > >                 # format=json to enable Ollama JSON mode
> > >                 temperature=0,
> > >             )
> > > 
> > > evaluator = DeepEvalFaithfulnessEvaluator(
> > >     model=model_local
> > > )
> > > ```
> > 
> > 
> > Do you also use this with synthesizer.generate* functions? If so, an example would be appreciated!
> 
> i edited my original answer.
> 
> i found a workaround by adding `def __class__(self)` at the end, now I'm able to use it as `synthesizer` in the following example:
> 
> ```python
> from deepeval.synthesizer import Synthesizer
> 
> model_local = OllamaLLM(model_name=model_name)
> 
> synthesizer1= Synthesizer(model=model_local)
> synthesizer.generate_goldens_from_contexts(
>     contexts=[
>         ["The Earth revolves around the Sun.", "Planets are celestial bodies."],
>         ["Water freezes at 0 degrees Celsius.", "The chemical formula for water is H2O."],
>     ]
> )
> ```

Thanks for the quick reply! I will try to modify my code using your example. 

I'm wondering, do you also run `deepeval set-local-model` through the terminal before using your code? I'm getting `openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable` errors if i don't. 

Also, i don't understand what `deepeval set-local-model` does. Is it a declaration for deepeval to use my local ollama directly or is it a way to tell deepeval that i will use local models somewhere in my code?

**Comment by 21m1n** [comment]
my understanding is that after running `deepeval set-local-model`,  a file named `.deepeval` containing your custom configuration will be created in the project home directory, which looks something like:

```
# .deepeval
{"LOCAL_MODEL_NAME": "llama3", "LOCAL_MODEL_BASE_URL": "http://localhost:11434/v1/", "LOCAL_MODEL_API_KEY": "ollama", "LOCAL_MODEL_FORMAT": "json", "USE_LOCAL_MODEL": "YES", "USE_AZURE_OPENAI": "NO"}
``` 

when you instantiate a new model object from the `GPTModel` class, a class method called `should_use_local_model()` is triggered to check if `.deepeval` exists. If it doesnt exist, the class will return a `ChatOpenAI` object which reuqires an `OPENAI_API_KEY` to be provided.

**Comment by amitguptaforwork** [comment]
for anybody getting this error
ollama._types.ResponseError: 404 page not found (status code: 404)

You can try removing the v1 from the ollama base url
deepeval set-local-model --model-name=llama3.2:1b --base-url="http://localhost:11434/" --api-key="ollama"

The .deepeval file can also be directly updated if it already got created.
