### ISSUE TITLE
Add RAGAS metrics to DeepEval

### ISSUE THREAD

**Issue by ColabDog** [confident-ai/deepeval#101]
Add RAGAS metrics to DeepEval. 
Key metrics that would be useful:
- Ragas Score (Harmonic mean) 
- Context Recall (for the retriever)

https://github.com/explodinggradients/ragas

**Comment by jjmachan** [comment]
Hey guys Jithin from the Ragas team here
excited about this integration that you guys are doing and would love to offer any help to make this possible 🙂 

cheers

**Comment by ColabDog** [comment]
Thanks @jjmachan !! Would love your help in adding RAGAS Score metric here. 
One thing we need to do is provide a binary score threshold if it's a success/failure though. Would you be able to help submit a PR? We have a guide on writing a custom metric here: https://docs.confident-ai.com/docs/quickstart/custom-metrics

Here's an example for Bias you can take a look at if you need installation help: https://github.com/confident-ai/deepeval/blob/main/deepeval/metrics/bias_classifier.py 

When contributing, we just use black for now :)

**Comment by jjmachan** [comment]
don't know when I'll get some cycles but when I do, I'll get to this :) . In the meantime, if getting on a call and helping design the implementation is useful to make it faster, I would love to!

**Comment by ColabDog** [comment]
No worries - I'd love to get on a call to discuss this! Do you have a calendly link? Otherwise - please feeli free to book something in my Calendly here: https://calendly.com/jacky-twilix/30min

**Comment by ColabDog** [comment]
FYI - I started the PR here #121   @jjmachan :)

**Comment by jjmachan** [comment]
awesome @ColabDog , excited to see that it is merged and try this out shortly. I've also booked a lot too

**Comment by ColabDog** [comment]
Sweet - looking forward to chatting. I wrote a bit of documentation here: https://docs.confident-ai.com/docs/measuring_llm_performance/ragas_score 

Would love for you to take a look and let me know if I missed anything!

**Comment by ColabDog** [comment]
Closing this issue for now that since the documentation is written.
