### ISSUE TITLE
[Question] What's the difference between Deepeval's RAG Evaluation and RAGAS

### ISSUE THREAD

**Issue by landhu** [confident-ai/deepeval#1015]
Deepeval have rag evaluation https://docs.confident-ai.com/docs/guides-rag-evaluation
And another repo can do rag evaluation: https://github.com/explodinggradients/ragas

**What's the difference between the two in rag evaluation?**

**Comment by penguine-ip** [comment]
@landhu similar implementation, more support into deepeval's ecosystem (concurrent execution, caching, verbose logs for debugging, integrate into Confident AI, etc)
