### ISSUE TITLE
Ability to tie TestResults with TestCases for batch runs

### ISSUE THREAD

**Issue by debdayal-aws** [confident-ai/deepeval#1019]
**❗BEFORE YOU BEGIN❗**
Are you on discord? 🤗 We'd love to have you asking questions on discord instead: https://discord.com/invite/a3K9c8GRGt

**Is your feature request related to a problem? Please describe.**
When we run a list of test cases as a batch there is no reliable way tie the test results back to test cases. 

**Describe the solution you'd like**
It would be nice if TestCase's fields like name, comment and additional_metadata fields are passed along to TestResult. Ideally I would prefer to have a unique id for each test case that I can assign and that unique id should be passed to TestResult, however if that is a lot of change then just passing down the name, comment and additional_metadata fields to TestResult would be really helpful.

**Describe alternatives you've considered**

**Additional context**

**Comment by penguine-ip** [comment]
@debdayal-aws supported on confident ai

**Comment by debdayal-aws** [comment]
Thank you @penguine-ip I have seen that name field however - I am not using Confident AI cloud - running batch using EvaluationDataset from a JSON file and collecting list of TestResult after executing evaluation(). The [TestResult](https://github.com/confident-ai/deepeval/blob/main/deepeval/evaluate.py) does not have the name field from TestCase --- `@dataclass
class TestResult:
    """Returned from run_test"""

    success: bool
    metrics_data: Union[List[MetricData], None]
    conversational: bool
    multimodal: Optional[bool] = None
    input: Union[Optional[str], List[Union[str, MLLMImage]]] = None
    actual_output: Union[Optional[str], List[Union[str, MLLMImage]]] = None
    expected_output: Optional[str] = None
    context: Optional[List[str]] = None
    retrieval_context: Optional[List[str]] = None`

**Comment by penguine-ip** [comment]
Hey please make a PR in that case, thanks!
