### ISSUE TITLE
ChromaDB dependency missing

### ISSUE THREAD

**Issue by fabiannagel** [confident-ai/deepeval#1038]
1. Follow this guide: https://docs.confident-ai.com/docs/evaluation-datasets-synthetic-data
2. Run `synthesizer.generate_goldens_from_docs()`
3. Get this error:

```
from chromadb.api.models.Collection import Collection
ModuleNotFoundError: No module named 'chromadb'
```

**Comment by penguine-ip** [comment]
docs updated here: https://docs.confident-ai.com/docs/evaluation-datasets-synthetic-data#1-generating-from-documents, thanks! @fabiannagel
