### ISSUE TITLE
How does one crete an account on https://www.confident-ai.com/?

### ISSUE THREAD

**Issue by danechitoaie** [confident-ai/deepeval#1044]
On pricing page (https://www.confident-ai.com/pricing) it says there's a free version you can use for testing.

"no credit card required*" yet you can't access anything unless you enter your credit card.
Then if you downgrade to free account you lose access as all you can see is a message with "No access to Confident AI".

**Comment by danechitoaie** [comment]
I'm sorry if this was the wrong place to ask this question, but not sure where else to do it as there's no contact form on the site.

**Comment by penguine-ip** [comment]
You can email ***@***.***, and to answer your question the
website is just outdated by one sentence. When you signed up it clearly
says start a 7 day free trial and you can cancel anytime, which it asked
for your card details, which is still free. When you downgrade it tells you
you will lose access so you should use your 7 days to decide if you like it
or not, I'm guessing you didn't read it and are confused for this reason.

**Comment by danechitoaie** [comment]
Ok. It's clear now. Thanks.
