### ISSUE TITLE
can we disable telemetry by default in python client? 

### ISSUE THREAD

**Issue by pritamsoni-hsr** [confident-ai/deepeval#1046]
**Describe the bug**

**To Reproduce**
1. add deepeval in any project, and start the service it without setting DEEPEVAL_TELEMETRY_OPT_OUT = YES

**Expected behavior**

telemetry should be disabled, otherwise deepeval gets a lot of private information from application

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by penguine-ip** [comment]
@pritamsoni-hsr hey not at the moment, happy to merge a quick PR on this

**Comment by pritamsoni-hsr** [comment]
hey @penguine-ip opened a PR for the fix, the CI seems to be failing tho

```
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
```

**Comment by penguine-ip** [comment]
Hey @pritamsoni-hsr we would accept a PR where there is an option to set opt out in python like
```
deepeval.disable_telemtry()
```

The current way of default opt out means we won't get feedback on what features are most popular.
