### ISSUE TITLE
Generation of goldens from docs in Synthesizer is not possible unless 

### ISSUE THREAD

**Issue by adesso-dominik-chodounsky** [confident-ai/deepeval#1069]
The `generate_goldens_from_docs` method of the `Synthesizer` class has a default attribute  `_send_data=True`, which triggers the wrapping up `_wrap_up_synthesis` method. However, unless a deepeval login is configured (which in my opinion should not be enforced), the function fails with the following exception:
`Exception: To push a dataset to Confident AI, please run `deepeval login` first.`

Expected behaviour would be to be able to call the function normally without the wrap up (so probably `_send_data=False` as default) and then have the option of saving the generated dataset manually.

Sample code:
```
synthesizer.generate_goldens_from_docs(
       document_paths=documents,
       max_goldens_per_context=1,
       max_contexts_per_document=1,
       chunk_size=64,
       chunk_overlap=0,
)

synthesizer.save_as(file_type="json", directory=EVAL_DATA_DIR)
```

If I add the parameter `_send_data=False` to the function, it seems to work, but this seems like an irregular workaround and is not documented in the docs, so a more natural mechanism would probably be better.

**Comment by penguine-ip** [comment]
@adesso-dominik-chodounsky It's not like that in the latest versions of deepeval

**Comment by adesso-dominik-chodounsky** [comment]
This is the current main:
https://github.com/confident-ai/deepeval/blob/8d0e8346f9f506a9833abd691be3b735c6651e19/deepeval/synthesizer/synthesizer.py#L123
