### ISSUE TITLE
Add a "not sure" / "unwilling to answer" metric

### ISSUE THREAD

**Issue by ColabDog** [confident-ai/deepeval#107]
Measure the amount of times an LLM is "unsure" of something or "unwilling" to answer. This is a growing pain point of LLMs. Not sure if research papers have caught up in this area unfortunately so some sort of Conceptual Similarity across a few such prompts should be the easiest way to do this.

**Comment by j-space-b** [comment]
Good call on this - this would be a subset of 'answer relevancy', correct?  If so, any thoughts on some kind of an integration between the 2 or is the 'not sure' metric envisioned to be seperate?
https://github.com/confident-ai/deepeval/blob/main/tests/test_answer_relevancy.py

**Comment by ColabDog** [comment]
Yep that's a really really good point. Currently - I see it as 2 separate metrics and but what we can do is add an overarching "Answer Relevancy" metric that then shows a few ways to measure "Answer Relevancy".
