### ISSUE TITLE
Missing max_goldens_per_document argument in synthesizer.generate_goldens_from_docs

### ISSUE THREAD

**Issue by NaraSyuhei** [confident-ai/deepeval#1071]
Hello,

First of all, thank you for maintaining this amazing project. I’ve been using it recently and came across a potential issue.

In the function generate_goldens_from_docs（deepeval/deepeval/dataset/dataset.py）, it seems that the synthesizer's generate_goldens_from_docs method is called with a max_goldens_per_document argument. However, based on my investigation, I could not find max_goldens_per_document as an argument in the synthesizer's implementation of generate_goldens_from_docs.

https://github.com/confident-ai/deepeval/blob/8d0e8346f9f506a9833abd691be3b735c6651e19/deepeval/dataset/dataset.py#L527

I wanted to check if this argument should be supported or if it's an oversight in the documentation or code.

Thank you for your time and support! I'd appreciate any clarification on this.

**Comment by adesso-dominik-chodounsky** [comment]
I second this, currently, the Synthesizer supports the following two related parameters:
- `max_goldens_per_context`
- `max_contexts_per_document`

**Comment by penguine-ip** [comment]
@NaraSyuhei @adesso-dominik-chodounsky thanks so much! out in v1.3.6
