### ISSUE TITLE
Upon failing a certain test, deepeval could print the LLM's output

### ISSUE THREAD

**Issue by adesso-dominik-chodounsky** [confident-ai/deepeval#1072]
I hope I did not overlook something, but I could not find/figure out how to get deepeval's `assert_test` function to print the evaluated LLM's answer in the shown report.

The report shows that for the given test case and metric, the test failed and gives the reason why, but it would be nice to be able to specify that the LLM's output should be included in the report for debugging reasons. Perhaps context too, I would suggest having the two separate, as the context may often be quite long.

**Comment by penguine-ip** [comment]
@adesso-dominik-chodounsky Hey! Its not possible to print everything in a user friendly way since its just the terminal we're writing to. Do you have some other methods in mind?
