### ISSUE TITLE
dataset.generated_goldens buggy because of wrong type of evolutions

### ISSUE THREAD

**Issue by amgonzalezd** [confident-ai/deepeval#1077]
While trying to use EvaluationDataset().generate_goldens the following error appeared: 

```
AttributeError: 'list' object has no attribute 'keys'
in Synthesizer._a_evolve_input(self, input, num_evolutions, evolutions, context, progress_bar)
    883 evolutions_used = []
    884 for _ in range(num_evolutions):
    885     # Randomize Evolution
    886     evolution_type = random.choices(
--> 887         list(evolutions.keys()), list(evolutions.values())
    888     )[0]
    890     # Create Evolution Prompt
    891     if isinstance(evolution_type, Evolution):
```

This is beacuse the default evolutions of the EvaluationDataset().generate_goldens is a list, while the needed object for synthesizer.generate_goldens() is a dictionary with the fractions. 

If I have analyzed this error correctly, please change the Default type of generate_goldens in the evaluation dataset. Thank you!

**Comment by AhmedGharbi96** [comment]
Any update on this issue please ? I had the same problem.

**Comment by NaraSyuhei** [comment]
I'm sorry, I hadn't read this issue before and ended up creating a duplicate issue. I believe the root cause is related to what I mentioned in my issue: the default values for the evolutions argument seem to be incorrect.

https://github.com/confident-ai/deepeval/issues/1085
