### ISSUE TITLE
Wrong interpretation of the result of Hallucination

### ISSUE THREAD

**Issue by anotine10** [confident-ai/deepeval#1082]
I understand that if it is a "yes", there is alignement with context, and if there is "no", there is contradiction. However when you assign the verdicts to the list "contradictions" or "factualalignements", you add the verdicts with a "no" inside the factualalignements instead of contradiction

https://github.com/confident-ai/deepeval/blob/3ce770c2a512d64c84d2aa07dd2e3879beda2bbc/deepeval/metrics/hallucination/hallucination.py#L119

**Comment by penguine-ip** [comment]
Hey @anotine10 totally, thanks for bringing this up, changing it right now :)

**Comment by sahibpreetsingh12** [comment]
@penguine-ip is this closed or do we need help here?

**Comment by penguine-ip** [comment]
Hey @sahibpreetsingh12  its closed and out in the latest release, appreciate it!
