### ISSUE TITLE
evolutions argument should be of type Dict[Evolution, float] instead of List[Evolution]

### ISSUE THREAD

**Issue by NaraSyuhei** [confident-ai/deepeval#1085]
Hello,

Thank you once again for your ongoing improvements to this project. I've been using it actively and noticed another potential issue.

In the current implementation of the generate_goldens_from_docs function, the evolutions argument is defined as List[Evolution]. However, it seems that the correct type should be Dict[Evolution, float], as each evolution might require a weight or priority for generating goldens.

Here is the relevant portion of the code:

https://github.com/confident-ai/deepeval/blob/dd64174925ccbacd4bb1feb332a9dcce29d87bc3/deepeval/dataset/dataset.py#L511

I believe allowing the evolutions argument to accept weights would offer more flexibility, enabling users to prioritize evolutions. Could you please confirm if this adjustment would be appropriate?

Thank you again for your hard work, and I look forward to your feedback.

**Comment by penguine-ip** [comment]
@NaraSyuhei Thanks for bringing this up! Will change the typing to avoid any confusion :)
