### ISSUE TITLE
Litellm integration request

### ISSUE THREAD

**Issue by ranjancse26** [confident-ai/deepeval#110]
I think it's a good idea to integrate with the Litellm as it provides an easy to integrate with 100+ LLMs.

https://github.com/BerriAI/litellm

LLM as a drop in replacement for GPT. Use Azure, OpenAI, Cohere, Anthropic, Ollama, VLLM, Sagemaker, HuggingFace, Replicate (100+ LLMs)

**Comment by ColabDog** [comment]
Hey - yeah! We're planning to integrate with them very soon :)

**Comment by ColabDog** [comment]
Update on this - I'll be writing a guide on how to use Litellm with us instead of a full-blown integration. 
Should just be a few lines of code!

**Comment by ColabDog** [comment]
https://litellm-git-fork-colabdog-feature-add-deepeval-clerkieai.vercel.app/docs/tutorials/deepeval
