### ISSUE TITLE
Add `tools_called_key_name` and `expected_tools_key_name` to both .add_test_cases_from_json_file() and .add_test_cases_from_csv_file() methods

### ISSUE THREAD

**Issue by rayenf-mw** [confident-ai/deepeval#1122]
I find it to be such an easy and straightforward fix, and it is frustrating to have to change the library code in order to make it work for my case and I imagine many other people would appreciate this addition.

I feel like it would make sense for the .add_test_cases_* methods to include all parameters of the constructor for the LLMTestCase class, hence why I am writing this issue (which I hope gets resolved soon) in order to just add these few parameters in said methods.

Attached below is a screenshot of what I attempted to do as a quick fix, however you are more aware of the effect this has on the codebase. If it breaks something somewhere else, a similar solution would probably take not much more effort than changing a few lines.

![image](https://github.com/user-attachments/assets/d392948b-c522-42c5-ac1f-b89db35e7055)

**Comment by penguine-ip** [comment]
@rayenf-mw can you please make a PR on this?

**Comment by penguine-ip** [comment]
@rayenf-mw its out!
