### ISSUE TITLE
'Answer Length' metric

### ISSUE THREAD

**Issue by j-space-b** [confident-ai/deepeval#113]
aka 'Brevity' metric.  Simple character count of answer (this metric might be somewhere else in the code but I'm not seeing it?)  Some models could score higher on relevancy but with more words (in theory) - an 'answer length' metric would control for that.

**Comment by ColabDog** [comment]
This is a great point. I like this metric - i added it as a custom metric with a very simple implementation here but never thought about having it as an official metric but I can see the use case for it. Feel free to submit a PR - would love to take a look! 
https://docs.confident-ai.com/docs/quickstart/custom-metrics

**Comment by j-space-b** [comment]
PR here - looks like it failed a lint formatting curious what you're using and what I could run it by locally - wasn't sure how to incorporate other than just what it is - used same as your custom metric but checks for > 1 character and returns 'AnswerLength' 
https://github.com/confident-ai/deepeval/pull/118

**Comment by ColabDog** [comment]
This was merged and closed :)
