### ISSUE TITLE
OpenAI Rate Limit Exceeds

### ISSUE THREAD

**Issue by Miriam2040** [confident-ai/deepeval#1132]
I am trying to run evaluate on my dataset with one metric (relevancy) and imeeidtaely get errors on getting to OpenAI rate limits, how to solve it? 

Event loop is already running. Applying nest_asyncio patch to allow async execution...
Evaluating 80 test case(s) in parallel: |          |  0% (0/80) [Time Taken: 00:00, ?test case/s]ERROR:root:OpenAI rate limit exceeded. Retrying: 1 time(s)...

**Comment by penguine-ip** [comment]
I think you have to see whether your openai is being used elsewhere because one metric run wouldn't cause a rate limit error

**Comment by meisin** [comment]
I got the same issue as@miriam2040. Initially it was running fine, then suddenly i get this error.
