### ISSUE TITLE
Number of golden records in output is not the same as requested in input during synthesis

### ISSUE THREAD

**Issue by nalin-programmer** [confident-ai/deepeval#1179]
Hi, I am facing an issue with response of golden records of synthesizer.
Even if I put max_goldens_per_document=1, it still returns 30+ records in response

```
params = {
            "synthesizer": self.synthesizer,
            "document_paths": ['path/to/document.pdf'],
            "max_goldens_per_document": 1,
            "include_expected_output": True,
            "chunk_size": 1024,
            "chunk_overlap": 0,
            "num_evolutions": 3
        }
        filtered_params = {k: v for k, v in params.items() if v is not None}
        dataset = EvaluationDataset()
        dataset.generate_goldens_from_docs(**filtered_params)
```

**Comment by penguine-ip** [comment]
Hey @nalin-programmer, the docs from generate from context is outdated unforunately so actually the max goldens per document parameter isn't really doing anything, will show the updated docs soon but in the meantime we recommend using the method outside of the dataset and do it separately via the synthesizer: https://docs.confident-ai.com/docs/synthesizer-generate-from-docs#generate-your-goldens

**Comment by nalin-programmer** [comment]
Thanks for the help

**Comment by penguine-ip** [comment]
@nalin-programmer no problem
