### ISSUE TITLE
Metric for  Answer Precision/Completeness

### ISSUE THREAD

**Issue by enrico-stauss** [confident-ai/deepeval#1213]
# Answer Precision/Completeness
I was going through the existing metrics and realized that there does not seem to be one that measures whether the `actual_answer` contains all information as per the `expected_answer` and maybe how similar it is in terms of detail or extent.

As this usecase does not sound very niche to me, I'd expect that this has been considered before. If that is the case, can someone please point me to a discission on the subject?
If there is no good reason, would you be interested in a PR that adds such metric to deepeval?

**Comment by penguine-ip** [comment]
Hey @enrico-stauss often times for a simple comparison a GEval metric will be enough. Simply ask it to compare the actual output and expected output and it will work. The advantage of this is it leaves the definition of what is considered "information" up to the user to define. But of course it involves a few extra minutes of setup, let me know if it doesn't work for you?

GEval docs: https://docs.confident-ai.com/docs/metrics-llm-evals#example

**Comment by enrico-stauss** [comment]
@penguine-ip  you're right that solves it for me. Thanks!
