### ISSUE TITLE
HallucinationMetric

### ISSUE THREAD

**Issue by ColabDog** [confident-ai/deepeval#131]
To check for hallucination, we can perform the following:
- [ ] Grab sources from a Google Search/Query
- [ ] Run Factual Consistency On Top

**Comment by j-space-b** [comment]
this is cool - needs an additional API possibly for google search?  If so are there any alternatives for web search?

**Comment by ColabDog** [comment]
For this, we can use Serp API (https://serpapi.com/) but unfortunately it's pretty expensive.  
I also potentially think we should be using Wikipedia data dumps to ensure factual correctness as opposed to just Google Search because it's also a better resource than Google Search in trustworthiness. Will explore what we can do here.
