### ISSUE TITLE
Add "logical fallacy" check to model output

### ISSUE THREAD

**Issue by j-space-b** [confident-ai/deepeval#132]
I'd added FallacyChain to LangChain last month (checks for logical fallacies) - link below - thinking I could add similar functionality to natural language model output here - thoughts?
https://python.langchain.com/docs/guides/safety/logical_fallacy_chain

**Comment by ColabDog** [comment]
This is very interesting - how would one capture the the degree of logical fallacy?

**Comment by j-space-b** [comment]
It could return a dictionary of logical fallacies but I think better for evaluation purposes a % of logical fallacies (with the denominator being sentence count) but returning a float.
