### ISSUE TITLE
AnswerRelevancyMetric generates inaccurate scores - failing a test that should pass

### ISSUE THREAD

**Issue by drawal1** [confident-ai/deepeval#175]
**Describe the bug**
AnswerRelevancyMetric scores are very low (0.001 - 0.28) when they should be closer to 0.7-0.8 for the (question, answer) tuple being tested

**To Reproduce**
Run the code below:
```
    post = "Summarize the access review status and tell me what should I do next?"
    response = """
The access review is at the initial stage with no clusters reviewed yet. Currently, the risky entitlements cluster (Cluster ID: -1) with 2 normal entitlements is pending review. There are 3 less-risky clusters (Cluster IDs: 0, 1, 2) with varying numbers of normal and anomalous entitlements. Start with the largest cluster and review all the normal entitlements first, then carefully review the anomalous ones. After that, you should proceed with the less-risky clusters.
"""
    # evaluate the response for relevancy
    relevancy_metric = AnswerRelevancyMetric(minimum_score=0.9)
    test_case = LLMTestCase(query=post, output=response)
    assert_test(test_case, [relevancy_metric])
```

**Expected behavior**
Test should pass

**Comment by ColabDog** [comment]
Thanks for this! For this situation, we use cross-encoders. I think the model under-performs when the answers and questions are asymmetric in length. I'll run some tests and update this to provide a new answer relevancy alternative - thanks for flagging! 

For the summarization use case, I'm thinking of adding a "SummarizationAccuracy" metric that is more closely aligned with the SummaC implementation - https://github.com/tingofurro/summac

I'll keep this issue alive until the PR is made
