### ISSUE TITLE
Bug when following documentation

### ISSUE THREAD

**Issue by georgepoly-maker** [confident-ai/deepeval#196]
**Describe the bug**
Trying to run the code present here 
https://docs.confident-ai.com/docs/quickstart/

**To Reproduce**
1. Using spyder or Vs code run this snippet 
from deepeval.dataset import create_evaluation_query_answer_pairs

dataset = create_evaluation_query_answer_pairs(
    openai_api_key="open AI key here",
    context="FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.7+ based on standard Python type hints.",
    n=13,
)

dataset.review()

It gives the error 
Traceback (most recent call last):
  File "/Users/george.polychronopoulos/Downloads/BidBot/utils/dpev.py", line 3, in <module>
    dataset = create_evaluation_query_answer_pairs(
  File "/Users/george.polychronopoulos/anaconda3/lib/python3.10/site-packages/deepeval/dataset.py", line 583, in create_evaluation_query_answer_pairs
    query=response["query"],
TypeError: string indices must be integers

**Expected behavior**
Trying to run the code present here:
It should load a dataset

**Screenshots**

**Desktop (please complete the following information):**
MACos latest

![error](https://github.com/confident-ai/deepeval/assets/105718075/f4063c10-6a7b-4f61-a7ab-2ba0a5622ea3)

**Comment by ColabDog** [comment]
This should be fixed in the latest release - let me know if there are any issues there
