### ISSUE TITLE
Factual consistency metric calculation is incorrect

### ISSUE THREAD

**Issue by MadinaKamolova** [confident-ai/deepeval#219]
**Describe the bug**
In factual_consistency.py the factual consistency metric calculation is incorrect (see lines 55-58). This is how I'm reading your code: Context is chunked into a list of strings; then each chunk is compared to the output; whichever chunk has the highest score -- that score becomes the "overall" evaluation score. If that's true, then you compare only one piece (chunk) of the context to the entire output. However, evaluation should take entire context into account. If your entire context says "flowers can be deadly and poisonous", the chunk (n=20 characters) "flowers can be" will likely have a high comparison (in your case"evaluation") score to the output "flower can be beautiful and fragrant." In which case evaluation score will indicate an inaccurate relationship between your output and context.

Hope this helps.

**Comment by penguine-ip** [comment]
It certainly does Madina! It will be fixed in our next release (v0.20.12), really appreciate it!

**Comment by penguine-ip** [comment]
@MadinaKamolova It's now deprecated for now, added a new hallucination metric as a replacement: https://docs.confident-ai.com/docs/evaluation-metrics#hallucination, come join our discord! https://discord.com/invite/a3K9c8GRGt
