### ISSUE TITLE
Would it be possible to use opt-in schema for telemetry instead of opt-out?

### ISSUE THREAD

**Issue by chaliy** [confident-ai/deepeval#269]
**Is your feature request related to a problem? Please describe.**

The library tries to connect to the Sentry endpoint, also sentry_sdk seems to do some instrumentation of code.

**Describe the solution you'd like**
Instead of opt-out for telemetry, please default to opt-in. This will allow using your awesome library in more restrictive environments.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by penguine-ip** [comment]
@chaliy Got it! I'll cut a release immediately for tonight, appreciate the comment, will let you know immediately once it's out so you can pip install -U deepeval

**Comment by penguine-ip** [comment]
@chaliy Just cut a release does is opt out by default, also we have a discord community that I'm trying to grow, if you've discord please drop in and I'd love to chat there! https://discord.com/invite/a3K9c8GRGt
