### ISSUE TITLE
RAGAS metric issue

### ISSUE THREAD

**Issue by lewis-ljh** [confident-ai/deepeval#294]
Hey Im trying to use the RAGAS metrics and constantly running into this issue: 
pyarrow.lib.ArrowInvalid: Could not convert <built-in function input> with type builtin_function_or_method: did not recognize Python value type when inferring an Arrow data type

Im installing these dependencies before hand:
!pip install llama-index
!pip install -U deepeval
!pip install ragas

**Comment by lewis-ljh** [comment]
I also got this when trying to get the overall metric: 'RagasContextualRelevancyMetric' object has no attribute 'metrics' 
With this code:
def ragasonly(query,output,expected_output,context):
  ragas_metric = RagasMetric()
  test_case = LLMTestCase(
      input=query,
      actual_output=output,
      expected_output=expected_output,
      context=context,
  )
  score = ragas_metric.measure(test_case)
  return score

**Comment by penguine-ip** [comment]
Hey Lewis, can you try updating to the newest version of deepeval and show me the trace stack if the error still persists? Thanks! Also easier if you ask it on our discord: https://discord.com/invite/a3K9c8GRGt

**Comment by penguine-ip** [comment]
Replied in discord, closing the issue :)
