### ISSUE TITLE
Retrieval context removed

### ISSUE THREAD

**Issue by hguhlich** [confident-ai/deepeval#309]
The retrieval context is no longer part of the `LLMTestCase` as of [this commit](https://github.com/confident-ai/deepeval/commit/d94a854a3bf3464cb4f16367995784908925bd5c#diff-eaf87080789200606ea161c64f03eabd451634889dd5a33e0c506ba6ac41d616). Is this intended? I think, it makes a lot of sense to also test for the quality of the retrieved context.

If you really don't want to have that anymore, you should at least remove it from the documentation: https://docs.confident-ai.com/docs/evaluation-test-cases#retrieval-context

**Comment by penguine-ip** [comment]
Hey @hguhlich, it was removed because there are currently no metrics supporting ranking similarity, and also no evidence so far it is being used. Are you using it? Happy to add it back for our release early next week.

**Comment by hguhlich** [comment]
Shouldn't the [Contextual Relevancy Metric from RAGAS](https://docs.ragas.io/en/latest/concepts/metrics/context_relevancy.html) use the retrieval context? From [your documentation](https://docs.confident-ai.com/docs/evaluation-test-cases#retrieval-context): 

> Remember, context is the ideal retrieval results for a given input and typically come from your evaluation dataset, whereas retrieval_context is your LLM application's actual retrieval results.

So, comparing the context with the input doesn't make sense if the context should be relevant by definition. We should compare the retrieved context with the input.

**Comment by penguine-ip** [comment]
Definitely something I overlooked, thanks for taking the time to look through the commit history and pointing it out! The new release on Monday will contain the fixes. Also come join our discord if you're on there, would love to have you in the community: https://discord.com/invite/a3K9c8GRGt

**Comment by penguine-ip** [comment]
@hguhlich https://docs.confident-ai.com/docs/evaluation-metrics#ragas, its out, thanks!
