### ISSUE TITLE
add support for Azure Openai for LLM based testing

### ISSUE THREAD

**Issue by senthilkumarimuth** [confident-ai/deepeval#359]
**Is your feature request related to a problem? Please describe.**
Currently, for LLM based testing, it uses openai. it would be better if we can evaluate based on azure openai as well.
**Describe the solution you'd like**
add a method which accepts azure openai 
**Describe alternatives you've considered**
I could not use evalute LLM based due to this. I had to implement one myself.
**Additional context**

**Comment by penguine-ip** [comment]
@senthilkumarimuth I can definitely do this, however I have never worked with Azure OpenAI before nor do I have an Azure OpenAI deployment.

From what I can gather and correct me if I'm wrong, I'll need `AZURE_OPENAI_API_KEY`, `AZURE_OPENAI_ENDPOINT`,  `openai_api_version`, and ` azure_deployment_name`. Is there anything I've missed?

**Comment by penguine-ip** [comment]
Also please come to our discord for better communication and I can resolve the issue faster: https://discord.com/invite/a3K9c8GRGt

**Comment by senthilkumarimuth** [comment]
> @senthilkumarimuth I can definitely do this, however I have never worked with Azure OpenAI before nor do I have an Azure OpenAI deployment.
> 
> 
> 
> From what I can gather and correct me if I'm wrong, I'll need `AZURE_OPENAI_API_KEY`, `AZURE_OPENAI_ENDPOINT`,  `openai_api_version`, and ` azure_deployment_name`. Is there anything I've missed?
> 
> 

Yes that's all you need.

**Comment by penguine-ip** [comment]
@senthilkumarimuth it's out! https://docs.confident-ai.com/docs/metrics-llm-evals#using-azure-openai

Version 0.20.36

**Comment by senthilkumarimuth** [comment]
> @senthilkumarimuth it's out! https://docs.confident-ai.com/docs/metrics-llm-evals#using-azure-openai
> 
> 
> 
> Version 0.20.36

So quick. Appreciate it. Let me some test cases then. Good day!

**Comment by penguine-ip** [comment]
Yes please let me know if it doesn't work, because I don't have an azure account so I couldn't test it.

**Comment by penguine-ip** [comment]
@senthilkumarimuth its done, new docs are here: https://docs.confident-ai.com/docs/metrics-introduction#using-azure-openai

Please join our discord for all future questions and 10/10 customer support :) https://discord.gg/a3K9c8GRGt
