### ISSUE TITLE
Bumping into issue with Ragas for calling context based evaluation

### ISSUE THREAD

**Issue by CJNA** [confident-ai/deepeval#369]
**Describe the bug**
There is an issue with ragas package function call for context based evaluation.
Not sure where to look as version is upto date.

`test_cases = LLMTestCase()
    @pytest.mark.parametrize(
        "test_cases",
        processed_dataset,
    )
    def test_case(test_cases: LLMTestCase):
        # Let's look at these metrics and how to set them https://docs.confident-ai.com/docs/evaluation-introduction
        # hallucination_metric = HallucinationMetric(minimum_score=0)
        answer_relevancy_metric = AnswerRelevancyMetric(minimum_score=0.9)
        contextMetric = ContextualRecallMetric(minimum_score=0.7, model="gpt-3.5-turbo")
>       evaluate([test_cases], [answer_relevancy_metric, contextMetric])

test_chatbot.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.venv/lib/python3.11/site-packages/deepeval/evaluate.py:122: in evaluate
    test_results = execute_test(test_cases, metrics, True)
../../.venv/lib/python3.11/site-packages/deepeval/evaluate.py:59: in execute_test
    metric.measure(test_case)
../../.venv/lib/python3.11/site-packages/deepeval/metrics/ragas_metric.py:263: in measure
    scores = evaluate(dataset, [context_recall])
../../.venv/lib/python3.11/site-packages/ragas/evaluation.py:89: in evaluate
    validate_column_dtypes(dataset)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ds = Dataset({
    features: ['question', 'ground_truths', 'contexts', 'id'],
    num_rows: 1
})

    def validate_column_dtypes(ds: Dataset):
        for column_names in ["question", "answer"]:
            if column_names in ds.features:
                if ds.features[column_names].dtype != "string":
                    raise ValueError(
                        f'Dataset feature "{column_names}" should be of type string'
                    )
    
        for column_names in ["contexts", "ground_truths"]:
            if column_names in ds.features:
                if not (
                    isinstance(ds.features[column_names], Sequence)
                    and ds.features[column_names].feature.dtype == "string"
                ):
>                   raise ValueError(
                        f'Dataset feature "{column_names}" should be of type'
                        f" Sequence[string], got {type(ds.features[column_names])}"
                    )
E                   ValueError: Dataset feature "contexts" should be of type Sequence[string], got <class 'datasets.features.features.Value'>

../../.venv/lib/python3.11/site-packages/ragas/validation.py:31: ValueError
=============================================================== slowest 10 durations ================================================================
3.39s call     test_chatbot.py::test_case[test_cases0]

(2 durations < 0.005s hidden.  Use -vv to show these durations.)
============================================================== short test summary info ==============================================================
FAILED test_chatbot.py::test_case[test_cases0] - ValueError: Dataset feature "contexts" should be of type Sequence[string], got <class 'datasets.features.features.Value'>`

**To Reproduce**

Call 
`    evaluate([test_cases], [answer_relevancy_metric, contextMetric])`
with 
`contextMetric = ContextualRecallMetric(minimum_score=0.7, model="gpt-3.5-turbo")`

**Expected behavior**
Expected evaluate to run.

**Screenshots**
<img width="1060" alt="Screenshot 2023-12-18 at 11 04 46 PM" src="https://github.com/confident-ai/deepeval/assets/23248772/082d7cc6-8100-4fcf-a8b9-2d0d359d1582">

**Desktop (please complete the following information):**
MacOS

DeepEval version ran:
[v0.20.39](https://github.com/confident-ai/deepeval/releases/tag/v0.20.39)
Ragas version:
ragas                        0.0.22

**Comment by penguine-ip** [comment]
Hey @CJNA, thanks for bringing this up. I updated the docs on context recall and it should work now!
