### ISSUE TITLE
OpenAI key setting on GitHub or in official document 

### ISSUE THREAD

**Issue by Dee-Ma** [confident-ai/deepeval#376]
**Is your feature request related to a problem? Please describe.**
When following the summarization metric example (used a default model `gpt-4-1106-preview`) from the official document [SummarizationMetric](https://docs.confident-ai.com/docs/metrics-summarization), the code returned an error of `Did not find openai_api_key, please add an environment variable 'OPENAI_API_KEY' which contains it, or pass  'openai_api_key' as a named parameter. (type=value_error)`. 

We have not find the corresponding settings from GitHub page or official document yet. 

**Describe the solution you'd like**
Can you please add some instructions about settings OpenAI Key in official examples? But please let me know if we just missed it. 

**Additional context**
Using the SummarizationMetric

**Comment by agokrani** [comment]
Hi @Dee-Ma,

You can just add OPENAI_API_KEY into your bashrc. You can get that api key from openai website.

**Comment by penguine-ip** [comment]
@agokrani That's right! 😊
