### ISSUE TITLE
Hard coded minimum score

### ISSUE THREAD

**Issue by senthilkumarimuth** [confident-ai/deepeval#393]
when we run a test case, we want to compare the LLM response matches with expected response. if match score is greater than MINIMUMSCORE, then we consider that the test is passed. I see that minimum score is hardcoded. can this be customizable by developer?

<img width="295" alt="Capture" src="https://github.com/confident-ai/deepeval/assets/81953865/03e879a1-4590-4e3e-b7ca-7a95a1ec44c9">

**Comment by penguine-ip** [comment]
Oh my goodness thanks for bringing this up, I've been trying to catch this bug forever! Will push out a release in a few hours to fix this.

**Comment by senthilkumarimuth** [comment]
okay, you just replace 0.5 with this

[image: image.png]

**Comment by penguine-ip** [comment]
@senthilkumarimuth by the way I don't know have you seen but Azure OpenAI is not supported: https://docs.confident-ai.com/docs/metrics-introduction#using-azure-openai

**Comment by senthilkumarimuth** [comment]
Thank you.

Can you add latency as well of the metric?
