### ISSUE TITLE
Dataset cross pollution bug

### ISSUE THREAD

**Issue by jeffometer** [confident-ai/deepeval#430]
**Describe the bug**
I had a hard time figuring out exactly where the bug is, but this is what I'm seeing.  

I want to create 2 datasets;

```
ds1 = EvaluationDataset()
ds2 = EvaluationDataset()
```

So far so good.  Now I make a test and add it to ds1

```
    t1 = LLMTestCase(
        id="t1",
        input="input",
        ...
    )
    ds1.add_test_case(t1)
```

Still good.  Now I add a new test to ds2

```
    t2 = LLMTestCase(
        id="t2",
        input="input",
        ...
    )
    ds2.add_test_case(t2)
```

No longer good.  Running `ds1.evaluate([metric1])` has *2* test cases in it (t1 and t2).  I expected only 1 (t1).

This is on OSX using 3.11.5 and deepeval  v0.20.51 (the previous version has the same issue)

Thank you for any help!

**Comment by jeffometer** [comment]
Aha!  I figured it out.  Because I called `EvaluationDataset()` with no argument, the default literal `[]` was used, but that default instance will be used for all new instances of EvaluationDataset.  
See https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments if I wasn't clear.
I'll make a PR, in the meantime you can do `EvaluationDataset([])` or append tests to an empty list and set `EvaluationDataset().test_cases = my_tests`.

**Comment by penguine-ip** [comment]
Hey @jeffometer , I saw your PR earlier this week (merged and live) but I missed your issue. That's for the thoughtful explanation! Some contributors are also talking here: https://discord.com/invite/a3K9c8GRGt
