### ISSUE TITLE
Inconsistent version between release page & pypi

### ISSUE THREAD

**Issue by codesbya8h1** [confident-ai/deepeval#471]
**Describe the bug**
* There's an inconsistency between the [release page](https://github.com/confident-ai/deepeval/releases) version and the latest version on [pypi.com](https://pypi.org/project/deepeval/)  also https://libraries.io/pypi/deepeval shows the stale version.
* When clicked on `Homepage` option on pypi website, it throws 404, and does not link back to Confident-AI, makes the origin of the owner unknown also there's no documentation.

**To Reproduce**
1. Go to https://github.com/confident-ai/deepeval/releases look for latest version
2. Compare the version on https://pypi.org/project/deepeval
3. Go to https://pypi.org/project/deepeval/ click on Homepage

**Expected behaviour**
* The package should have latest version and necessary information on the Pypi website to establish its authenticity. 

**Additional context**
Deepeval provides some really good features for Test Cases for LLMs however to use it, one needs to be sure that the latest version is up to date at all the places and is any kind of risk free also be able to establish a relationship to the Confident-AI(Package Owner)by providing necessary documentation and path to websites like homepages. Due to these inconsistencies I am unable to decide on which version to use/trust between pypi & release page.

**Comment by penguine-ip** [comment]
Thanks for bringing this up, fixed!
