### ISSUE TITLE
SummarizationMetric and empty set of assessment_questions

### ISSUE THREAD

**Issue by qgrail** [confident-ai/deepeval#495]
Hi, 
I am using the **SummarizationMetric** to evaluate the output of a LLM.
In the blog post example [here](https://docs.confident-ai.com/docs/metrics-summarization#example) you say that _If assessment_questions is not provided, we will generate a set of assessment_questions for you at evaluation time._

However, I wasn't able to find where these questions are generated in the code and, on my side, I always end up with `assessment_question` being `None`; thus an `inclusion_score` of 1 from this [line](https://github.com/confident-ai/deepeval/blob/51d5d2d3c337a3d3ee9a7e5005adadbc3da46a8d/deepeval/metrics/summarization.py#L163).

Could you help me on this issue?

Thanks

Edit: I am using latest version `0.20.68`

**Comment by penguine-ip** [comment]
Hey @qgrail ! Yes, we got complaints that the generated questions were too arbitrary and so removed it for the time being. It is the blog that needs updating (or unless we have a better way to make the generated assessment questions more aligned with expectations)

**Comment by qgrail** [comment]
Understand, thanks for the clarification.

**Comment by penguine-ip** [comment]
@qgrail actually bringing the inclusion score back tomorrow with auto generated assessment questions, but also renaming it to coverage score (inclusion will be used for diversity & inclusion instead)
