### ISSUE TITLE
Getting `JSONDecodeError` error when running simple `AnswerRelevancyMetric` example

### ISSUE THREAD

**Issue by ymzayek** [confident-ai/deepeval#499]
**Describe the bug**
I'm getting a `JSONDecodeError` when trying to run a simple example based off one of your examples but using a custom model with prometheus13b llm model. It seems to come from https://github.com/confident-ai/deepeval/blob/68d1f59b3aa23d184e7a3b1ae731ce126ab89863/deepeval/utils.py#L98

Below I provide reproducible code, the print of `jsonStr` variable a,d the full traceback

**To Reproduce**
<details>
  <summary>Reproducible code</summary>

```python
from deepeval.metrics import AnswerRelevancyMetric
from deepeval.test_case import LLMTestCase
from transformers import AutoModelForCausalLM, AutoTokenizer
from deepeval.models.base import DeepEvalBaseLLM
import json


# name of model to use as the LLM evaluator
# model_name = "kaist-ai/prometheus-7b-v1.0"
model_name = "kaist-ai/prometheus-13b-v1.0"
# Derived from https://docs.confident-ai.com/docs/metrics-introduction#mistral-7b-example
class CustomModel(DeepEvalBaseLLM):
    def __init__(
        self,
        model,
        tokenizer
    ):
        self.model = model
        self.tokenizer = tokenizer

    def load_model(self):
        return self.model

    def _call(self, prompt: str) -> str:
        model = self.load_model()

        device = "cuda"  # the device to load the model onto

        model_inputs = self.tokenizer(
             [prompt], return_tensors="pt"
        ).to(device)
        model.to(device)

        generated_ids = model.generate(
             **model_inputs, max_new_tokens=100, do_sample=True
        )
        return self.tokenizer.batch_decode(generated_ids)[0]

    def get_model_name(self):
        return "Custom model"


# create custom model from custom class
model = AutoModelForCausalLM.from_pretrained(
     model_name,
     torch_dtype="auto",
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

custom_model = CustomModel(model=model, tokenizer=tokenizer)

# Output of LLM application
actual_output = "We offer a 30-day full refund at no extra costs."

# Replace this with the actual retrieved context from your RAG pipeline
retrieval_context = [
    "All customers are eligible for a 30 day full refund at no extra costs."
]

input = "What if these shoes don't fit?"

metric = AnswerRelevancyMetric(
    threshold=0.5,
    model=custom_model,
    include_reason=True,
)
test_case = LLMTestCase(
    input=input,
    actual_output=actual_output,
    retrieval_context=retrieval_context,
)

metric.measure(test_case)
print(metric.score)
print(metric.reason)
```

</details>

**Desktop (please complete the following information):**
 - Debian 12

**Additional context**

Print of jsonStr variable:

```json
{
    "statements": ["Shoes.", "Shoes can be refunded at no extra cost", "Thanks for asking the question!"]
}
===== END OF EXAMPLE ======
        
Text:
We offer a 30-day full refund at no extra costs.

**
IMPORTANT: Please make sure to only return in JSON format, with the "statements" key as a list of strings. No words or explaination is needed.
**

JSON:
{
    "statements": ["We", "offer", "a", "30-day", "full", "refund", "at", "no", "extra", "costs"]
}
```

<details>
  <summary>Full traceback</summary>

```bash
Traceback (most recent call last):
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/site-packages/deepeval/utils.py", line 98, in trimAndLoadJson
    return json.loads(jsonStr)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 4 column 1 (char 110)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yasmin/ia/llm-eval/deepeval/tests/evaluate.py", line 81, in <module>
    metric.measure(test_case)
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/site-packages/deepeval/metrics/answer_relevancy.py", line 46, in measure
    self.statements: List[str] = self._generate_statements(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/site-packages/deepeval/metrics/answer_relevancy.py", line 119, in _generate_statements
    data = trimAndLoadJson(res)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/yasmin/micromamba/envs/deepeval/lib/python3.11/site-packages/deepeval/utils.py", line 100, in trimAndLoadJson
    raise ValueError(
ValueError: Error: Evaluation LLM outputted an invalid JSON. Please use a better evaluation model.
```

</details>

**Comment by AndresPrez** [comment]
@ymzayek Im getting similar error... Notice your `statements`...

In my case I was Google's Text Bison model with temperature 0.0. I noticed that the resulting `statements` that are getting generated from deepeval's prompt when using cheaper models like ours does not work very well. Now since the `answer` is getting split into a very long list of these "statements" the models try to generate an equally long output JSON, however these cheaper models also tend to have an max output token limitation so the generated JSON gets truncated and deepeval code fails to parse it/

**Comment by ymzayek** [comment]
Ok thanks for the explanation. I was getting to the same conclusion but had misunderstood a bit about Prometheus as well wanting to run a quick test of an evaluation pipeline. Do you have recommendations of models to use outside of GPT if I wanted to specifically focus on evaluating a chatbot that uses RAG?

**Comment by penguine-ip** [comment]
@ymzayek I used to recommend mistral 7B, until more and more users started reporting problems around generating valid JSON outputs. I can't guarantee Llama2 as well, I heard you need some fine-tuning to get it to work better. What's the main concern with OpenAI? If it is data security, there's an option for azure openai.

Here's an example of how someone else managed to get their open source model to output JSON, I"m not so familiar with it but i'm going to link it in case you find it helpful: https://christophergs.com/blog/ai-engineering-evaluation-with-deepeval-and-open-source-models#simple (scroll down a little to "A more complex example")

We have a discord by the way, come join us: https://discord.com/invite/a3K9c8GRGt

**Comment by penguine-ip** [comment]
@ymzayek I'm glad it worked out, we'll be pushing more improvements to GEval as well by end of week :)

**Comment by penguine-ip** [comment]
Hey @ymzayek , I was wondering can you show me your mistral example? I've a few folks asking how to use grammar files with mistral 7B but i only have the example for llama

**Comment by ymzayek** [comment]
@penguine-ip my code is pretty much the same as the last code block in the [link you sent me](https://christophergs.com/blog/ai-engineering-evaluation-with-deepeval-and-open-source-models#simple). I'm using `"TheBloke/Mistral-7B-Instruct-v0.2-GGUF"` file `"mistral-7b-instruct-v0.2.Q5_K_M.gguf"` for the custom model and this [JSON grammar file](https://github.com/ggerganov/llama.cpp/blob/master/grammars/json.gbnf) from llamacpp to constrain to JSON.

See snippet:

<details>
  <summary>Python script</summary>

Replace input and actual_output given to `LLMTestCase` with own data and put `json.gbnf` in path and this should run as is:

```python
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.models.base import DeepEvalBaseLLM
from llama_cpp import Llama, LlamaGrammar


class CustomModel(DeepEvalBaseLLM):
    def __init__(
        self,
        model,
    ):
        self.model = model

    def load_model(self):
        return self.model
    
    def load_grammar(self):
        file_path = "./json.gbnf"
        with open(file_path, "r") as handler:
            content = handler.read()

        return LlamaGrammar.from_string(content)

    def _call(self, prompt: str) -> str:
        model = self.load_model()

        response = model.create_completion(
            prompt,
            max_tokens=-1, 
            grammar=self.load_grammar()
        )

        return response["choices"][0]["text"]

    def get_model_name(self):
        return "Custom model"


model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
filename = "mistral-7b-instruct-v0.2.Q5_K_M.gguf"
llm = Llama.from_pretrained(
    repo_id=model_name,
    filename=filename,
    n_ctx=4096,
    n_batch=8,
    chat_format="mistral-instruct",
)
custom_model = CustomModel(model=llm)

coherence_metric = GEval(
    name="Coherence",
    model=custom_model,
    criteria="Coherence - determine if the actual output is coherent with the input.",
    evaluation_params=[
        LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT
    ],
)

test_case = LLMTestCase(
    input=data["input"].iloc[0],
    actual_output=data["output"].iloc[0],
)

coherence_metric.measure(test_case)
coherence = coherence_metric.score
```

I haven't found a way to make it work reliably without using llamacpp and even with the llamacpp set up it doesn't work reliably with any model. Mistral 7b instruct and mistral 7b should both work fine but with bigger models it tends to fail sometimes.

**Comment by penguine-ip** [comment]
@ymzayek thank you so much! Its very helpful. GEval also got improved and we now use async instead of threading so your segmentation fault shouldn't be there anymore. Have a nice day.
