### ISSUE TITLE
2KAttributeError: 'AIMessage' object has no attribute 'find'

### ISSUE THREAD

**Issue by piseabhijeet** [confident-ai/deepeval#502]
**Describe the bug**
Cannot run metrics on custom Azure OpenAI model

**To Reproduce**

```
import openai
from deepeval.models.base import DeepEvalBaseLLM
from azure.identity import AzureCliCredential
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from langchain.chat_models import AzureChatOpenAI
from deepeval.metrics import AnswerRelevancyMetric, ContextualRelevancyMetric
from deepeval.metrics import HallucinationMetric


class DeepEvalAzureOpenAI(DeepEvalBaseLLM):
    def __init__(
        self,
        model
    ):
        self.model = model

    def load_model(self):
        return self.model

    def _call(self, prompt: str) -> str:
        chat_model = self.load_model()
        return chat_model.invoke(prompt)

    def get_model_name(self):
        return "Custom Azure OpenAI Model"


TENANT_ID = "xyzzy"
OPEN_AI_SCOPE = 'https://cognitiveservices.azure.com/.default'
MODEL_NAME = 'gpt-4-32k'
openai.api_base = 'https://xyz.azure.com/' 
openai.api_version = '2023-05-15'
 
# for AD:
openai.api_type = 'azure_ad'
token_credential = AzureCliCredential(tenant_id=TENANT_ID)
token = token_credential.get_token(OPEN_AI_SCOPE)
openai.api_key = token.token
custom_model = AzureChatOpenAI(
        deployment_name='gpt-4-32k',
        model_name="gpt-4-32k",
        openai_api_key=openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_version=openai.api_version
    )

azure_openai = DeepEvalAzureOpenAI(model=custom_model)


context=["A man with blond-hair, and a brown shirt drinking out of a public water fountain."]

actual_output="A blond drinking water in public."

test_case = LLMTestCase(
    input="What was the blond doing?",
    actual_output=actual_output,
    context=context
)
metric = HallucinationMetric(threshold=0.5, model=azure_openai)

metric.measure(test_case)
print(metric.score)


```
**Screenshots**
<img width="1030" alt="Screenshot 2024-02-22 at 19 31 42" src="https://github.com/confident-ai/deepeval/assets/57705684/6f7b8540-bd03-4cde-b358-3af348724e0c">

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)

**Additional context**
python package versions:
<img width="246" alt="Screenshot 2024-02-22 at 19 33 14" src="https://github.com/confident-ai/deepeval/assets/57705684/4c872157-a694-46c5-bdf9-1a5ddf2768f8">

python 3.10

**Comment by penguine-ip** [comment]
@piseabhijeet glad you resolved it, not your problem, we just updated the docs yesterday since there was a bug in the sample documentation that caused this error. Updated docs: https://docs.confident-ai.com/docs/metrics-introduction#azure-openai-example

**Comment by piseabhijeet** [comment]
@penguine-ip 

thank you for the prompt response! This seems to work!

Also, follow up question, when I try to run some metrics like hallucination, it gives a message saying log in to deepeval to see the results. are the results still getting logged? i am using a custom llm to evaluate, does confident-ai still save the data using telemetry to the servers?


<img width="1155" alt="Screenshot 2024-02-22 at 19 55 27" src="https://github.com/confident-ai/deepeval/assets/57705684/51cbe519-b0d1-477d-ba3c-ff0994f88c9f">

**Comment by penguine-ip** [comment]
@piseabhijeet No problem, and nope, it is just suggesting you should log in to keep track of results, its opinional. Also our telemetry only keeps track of the name of the metric being ran (so we know which metric is most popular and can optimize for those), and whenever someone runs an evaluation (so we can keep track how many people are running evaluations). 

Evaluation count logging: https://github.com/confident-ai/deepeval/blob/main/deepeval/telemetry.py#L19
Metric count logging: https://github.com/confident-ai/deepeval/blob/main/deepeval/telemetry.py#L24

**Comment by piseabhijeet** [comment]
@penguine-ip - super happy to hear that! And looking forward to using all the metrics from deepeval :)
