### ISSUE TITLE
Issues using Custom LLM on air gapped systems.  Remove __init__.py chech_for_update()

### ISSUE THREAD

**Issue by JoeSF49** [confident-ai/deepeval#506]
Importing DeepEvalBaseLLM hangs on air gapped system due to chech_for_update() process during init.

commenting out the request to function at end of init allows loading of Module  and usage of custom locally loaded LLM

**Comment by penguine-ip** [comment]
@JoeSF49 Thanks for bringing this up, do you know why it hangs? I'll add a timeout just in case

**Comment by JoeSF49** [comment]
a timeout would be great thanks.  it's just a secured system running a
workload with all the libraries and models locally and airg apped (no
internet access)

thanks

**Comment by penguine-ip** [comment]
@JoeSF49 I see, glad to know it isn't a bug but an edge case, I'll ping you once its out tomorrow

**Comment by penguine-ip** [comment]
@JoeSF49 Outdate is out, now has a 5 second timeout for the latest version v0.20.71

Also come join us on discord: https://discord.com/invite/a3K9c8GRGt
