### ISSUE TITLE
Missing dependency: detoxify

### ISSUE THREAD

**Issue by moruga123** [confident-ai/deepeval#512]
**Describe the bug**
ModuleNotFoundError: No module named 'detoxify'

**To Reproduce**
Run a python script with DeepEval imports

**Expected behavior**
All needed modules should be included in dependencies

**Screenshots**
Traceback (most recent call last):
  File "---", line 33, in <module>
    from deepeval.models.base import DeepEvalBaseLLM
  File "---/lib/python3.10/site-packages/deepeval/models/__init__.py", line 8, in <module>
    from deepeval.models.detoxify_model import DetoxifyModel
  File "---/lib/python3.10/site-packages/deepeval/models/detoxify_model.py", line 3, in <module>
    from detoxify import Detoxify
ModuleNotFoundError: No module named 'detoxify'

**Desktop (please complete the following information):**
 - OS: Linux

**Smartphone (please complete the following information):**

**Comment by penguine-ip** [comment]
@moruga123 have you tried `pip install detoxify`?

**Comment by penguine-ip** [comment]
also are you trying to use the detoxify metric? the latest version does not require detoxify

**Comment by moruga123** [comment]
This is working after changing to a clean venv with short requirement list
