### ISSUE TITLE
Allow users to configure embeddings for RAGAS metrics 

### ISSUE THREAD

**Issue by Li0425** [confident-ai/deepeval#513]
**Is your feature request related to a problem? Please describe.**
The versions of `deepeval` and `ragas` that I'm using:
- deepeval==0.20.70
- ragas==0.1.1

I was trying to use `RAGASAnswerRelevancyMetric` to evaluate the generated output of my Microsoft Azure Endpoints for the Open AI GPT models. Under the hood, in `ragas/evaluation.py`, embeddings are used for the calculation, and I cannot find a way to override the embeddings with the deepeval library. ragas library supports Microsoft Azure endpoints - their instruction:
"In order to use the library with Microsoft Azure endpoints, you need to set the OPENAI_API_TYPE, OPENAI_API_BASE, OPENAI_API_KEY and OPENAI_API_VERSION. The OPENAI_API_TYPE must be set to 'azure' and the others correspond to the properties of your endpoint. In addition, the deployment name must be passed as the model parameter."
I'm not sure how I can pass the deployment name as the model parameter to ragas from deepeval.

**Describe the solution you'd like**
I hope users of deepeval can have a better control over how embeddings are generated when using ragas-related metrics.

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

P.S. thanks for open-sourcing this great library.

**Comment by penguine-ip** [comment]
@Li0425 Hey! No problem, we'll support it

**Comment by penguine-ip** [comment]
@Li0425 It's done! Newest version 0.20.71, here are the docs: https://docs.confident-ai.com/docs/metrics-ragas#example

Note that only the RAGASAnswerRelevancy metric uses embeddings, it doesn't matter to the implementation but just as a piece of info :)

Come join our discord to talk :) : https://discord.com/invite/a3K9c8GRGt

**Comment by Li0425** [comment]
Hi @penguine-ip, thanks for the super quick update! Joined the discord 👍

**Comment by penguine-ip** [comment]
@Li0425 no problem :) and happy to have u

**Comment by Li0425** [comment]
Hello @penguine-ip , regarding this change: for answer relevancy it works well. However, for other ragas metrics that don't really calculate based on embeddings, embedding_factory() in ragas library would be hit anyways, and deepeval test couldn't be run again due to not able to configure combeddings

**Comment by penguine-ip** [comment]
@Li0425 Can you give an example? I thought only Answer relevancy uses embeddings. I tried using the RAGAS metric and didn't run into errors. 

Also come to discord if you're on there! https://discord.com/invite/a3K9c8GRGt I check it a lot more often
