### ISSUE TITLE
Pydantic v1 fallback for this part of the code

### ISSUE THREAD

**Issue by kubre** [confident-ai/deepeval#599]
I've seen other part of the code handle pydantic v1 case gracefully but this fails

https://github.com/confident-ai/deepeval/blob/97f528a9336b2cde9a2ba30787a25ac4331ddb37/deepeval/test_run/test_run.py#L95

**Comment by penguine-ip** [comment]
hey @kubre thanks for bringing this up! Do you know how it would look like? Happy to quickly approve a PR if you make one otherwise it will probably be next week before i can get around to this.

**Comment by kubre** [comment]
https://github.com/confident-ai/deepeval/pull/600#issue-2188203483
