### ISSUE TITLE
add_test_cases_from_json_file method creates retrieval_context from context_key_name parameter.

### ISSUE THREAD

**Issue by omarjaz** [confident-ai/deepeval#620]
**Describe the bug**
The `EvaluationDataset` method `add_test_cases_from_json_file` uses `context_key_name` parameter to create the `retrieval_context` for every `test_case`. `retrieval_context_key_name` parameter is then useless.

**To Reproduce**
1. Go to deepeval/dataset
2. Click on dataset.py
3. Scroll down to line 228
4. See error `retrieval_context = json_obj.get(**context_key_name)**`

**Expected behavior**
This method should create `retrieval_context` from `retrieval_context_key_name` parameter.
 `retrieval_context = json_obj.get(retrieval_context_key_name)`

Thanks!

**Comment by penguine-ip** [comment]
fixed in latest release
