### ISSUE TITLE
Error handling with customLLM models in metrics classes, returning a default option instead of throwing an error

### ISSUE THREAD

**Issue by AlexisGitHu** [confident-ai/deepeval#625]
**Is your feature request related to a problem? Please describe.**
When using a custom LLM, the metrics classes that use json outputs may throw an error due to incorrect json formatting. 

**Describe the solution you'd like**
These errors could be handled by repairing the json string into the correct formatting.

**Describe alternatives you've considered**
Other alternatives may include returning a default score or empty score for cases when error triggers. This could be documented instead of assuring that custom LLMs may not work.

**Additional context**
This may make the application more ready to use for production environments with no default LLM model.

**Comment by penguine-ip** [comment]
@AlexisGitHu fixed in latest release https://docs.confident-ai.com/docs/evaluation-introduction#ignore-errors
