### ISSUE TITLE
Question : Summarization metric with expected output

### ISSUE THREAD

**Issue by snassimr** [confident-ai/deepeval#637]
I want to evaluate summarization given actual summarization and run this code 

```
test_cases = [LLMTestCase(input=#text_to_summarize#, 
                          actual_output=#predicted_summary#,
                          expected_output=#actual_summary#]

dataset = EvaluationDataset(test_cases=test_cases)


metric = SummarizationMetric(
    threshold=0.5,
    model="gpt-4"
)

test_results = evaluate(dataset, [metric], print_results = False)
```

What are alignment and coverage components measure here ?

**Comment by penguine-ip** [comment]
Hey @snassimr for alignment it will check for hallucination + any irrelevant fluffs in your summary, while the coverage will check for the proportion of information that is included in your summary from your original text. 

Note that coverage is generated by randomly picking information in the original text and seeing whether it is in the summary. You might find yourself more tolerating than the coverage score, so typically a summarization score of 0.8 is pretty good.

Also can you ask on discord in the future? I'm starting to lose track of the issues: https://discord.com/invite/a3K9c8GRGt
