### ISSUE TITLE
Question: Using DeepEval with HuggingFace LLM

### ISSUE THREAD

**Issue by nikhilkomakula** [confident-ai/deepeval#638]
Hello,

Do you have a working example of using DeepEval with HuggingFace LLM without having to download the model to the local environment (like using HuggingFaceEndpoint)?

Thanks.

**Comment by penguine-ip** [comment]
@nikhilkomakula No we don't, but it should just be an API request. The important thing is the `generate` method should only accept the prompt (string) and output the generation (string)

**Comment by penguine-ip** [comment]
@nikhilkomakula If you come on our discord and share some code for your HugginFaceEndpoint i can give you an example: https://discord.com/invite/a3K9c8GRGt
