### ISSUE TITLE
Add Cohere command-r model support

### ISSUE THREAD

**Issue by fabian57fabian** [confident-ai/deepeval#660]
**❗BEFORE YOU BEGIN❗**
Are you on discord? 🤗 We'd love to have you asking questions on discord instead: https://discord.com/invite/a3K9c8GRGt

**Is your feature request related to a problem? Please describe.**
Allow users to use Cohere api with command-r model.

**Describe the solution you'd like**
Create a CohereModel class from DeepEvalBaseLLM according to https://docs.confident-ai.com/docs/metrics-introduction#using-a-custom-llm

**Describe alternatives you've considered**
Creating a personal class and copying between projects can be struggling.

**Additional context**
Cohere offers other models and one can experiment with them.

**Comment by EwoutH** [comment]
They now also released a larger, 104B parameter model: [C4AI Command R+](https://huggingface.co/CohereForAI/c4ai-command-r-plus)

**Comment by fabian57fabian** [comment]
> They now also released a larger, 104B parameter model: [C4AI Command R+](https://huggingface.co/CohereForAI/c4ai-command-r-plus)

I added a pull requests by inserting the class in the docs. Still waiting for reply.
This relies entirely on the cohere api, but i don't know if they allow what model to use or if the api key decides the model used.
Check out #661 PR

**Comment by penguine-ip** [comment]
just merged, TYSM! Would love to have you in our discord, especially when I start merging your docs into some tutorials for our users: https://discord.com/invite/a3K9c8GRGt

**Comment by penguine-ip** [comment]
> Tests are not running because poetry does not install cohere. Any idea how to change the poetry.lock file?

(dw about this, its fine)
