### ISSUE TITLE
Typo in faithfulness template

### ISSUE THREAD

**Issue by palaparthi** [confident-ai/deepeval#676]
**Describe the bug**
Typo in metrics/faithfulness/template.py, comphrensive -> comprehensive

![Screenshot 2024-04-10 at 12 27 51 PM](https://github.com/confident-ai/deepeval/assets/28518512/f098d5b6-2bd3-44b8-8f74-1eeb4c1a95df)

**Comment by penguine-ip** [comment]
@palaparthi thanks!
