### ISSUE TITLE
`deepeval test run` takes default pytest `addopts` with no option to override

### ISSUE THREAD

**Issue by shippy** [confident-ai/deepeval#683]
**Describe the bug**
`deepeval` inherits `pytest` `addopts` with no option to overrule them. (This means that by-default excluded evals cannot be run by `deepeval test run` under any circumstance.)

**To Reproduce**

1. Mark an arbitrary test `@pytest.mark.llm`
2. Add to `pyproject.toml` the following section:
```toml
[tool.pytest.ini_options]
markers = [
    "llm: mark tests with LLM involvement"
]
addopts = "-m 'not llm'"

```
4. Run `pytest` to check that default behavior applies and test is not run
5. Run `deepeval run tests`
6. Run `pytest -m llm` to check that the behavior is inverted
7. Run `deepeval test run -m llm`, or `deepeval test run path/to/excluded/test` to attempt (& fail) to invert the behavior with `deepeval`

**Expected behavior**
I'd expect that `deepeval` will allow me to overrule pytest default behavior with `-m` and other similar pytest-like switches (e.g. `-k`).

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1

**Additional context**
- Python: 3.11.8
- pytest: 8.1.1
- deepeval: 0.21.26

**Comment by penguine-ip** [comment]
@shippy Thank you so much!
