### ISSUE TITLE
Add functionality to calculate average score

### ISSUE THREAD

**Issue by ColabDog** [confident-ai/deepeval#70]
Add functionality to calculate average score across multiple runs. 

This ensures a fair comparison so you don't have to view the test run multiple times.

**Comment by lz039** [comment]
Is this possible now?

**Comment by atreyasha** [comment]
@ColabDog did you mean to compute the average of several calls, to mitigate the randomness in the LLM's outputs?

AFAIK this feature isn't there. @penguine-ip is this correct?

**Comment by penguine-ip** [comment]
@atreyasha Please start a new issue since this is pretty dated but we have some support for it: https://docs.confident-ai.com/docs/evaluation-introduction#repeats
