### ISSUE TITLE
Documentation for Chain of Thought in GEval

### ISSUE THREAD

**Issue by prescod** [confident-ai/deepeval#726]
**Is your feature request related to a problem? Please describe.**
When I read the documentation about GEval, it is incomplete.

The example code shows a `criteria` and `evaluation_steps` in the same flow. Furthermore, it shows
`evaluation_steps` with a single item, which is not very logical. If you had only one step, you would
use a criteria.

**Describe the solution you'd like**
I would like to see a realistic example of how evaluation_steps is meant to be used.

**Comment by penguine-ip** [comment]
@prescod I see what you mean, we didn't explain how the execution flow works for different scenarios of providing evaluation steps and criteria.. thanks for a feedback we'll include more description and examples!
