### ISSUE TITLE
LiteLLM Docs

### ISSUE THREAD

**Issue by krrishdholakia** [confident-ai/deepeval#78]
Hey guys, 

I see some LiteLLM docs in this repo - curious, did y'all fork it? Totally cool if so, just wondering why fork vs. using the package?

**Comment by ColabDog** [comment]
Hey nah - I just borrowed the layout of the documentation since you guys already set up Docusaurus - I'll make sure to remove all mentions of LiteLLM.

**Comment by ColabDog** [comment]
See #79
