### ISSUE TITLE
BiasMetric fails to return verdicts in release >=0.21.73

### ISSUE THREAD

**Issue by VVinayak** [confident-ai/deepeval#936]
**Describe the bug**
DeepEval's release 0.21.73 has a bug that causes no verdicts to be returned when anyone uses the BiasMetric. There is a missing return statement on a specific line in the repo - it must be an unintentional miss, but it is a breaking change for anyone using the BiasMetric with releases >=0.21.73.

https://github.com/confident-ai/deepeval/blob/c129492096594d676ab055345bfe372f7250d5a2/deepeval/metrics/bias/bias.py#L213

Whenever I run my cookbooks, they indicate no verdicts were given by the LLM, but that's only because of the lack of a return statement for verdicts after line 213. Anybody trying to compute bias using the latest DeepEval release on a dataset is probably getting the same error as me because the calculation of bias depends on the total number of verdicts, which is currently 0 if you are using your own LLM instead of the native model.

**To Reproduce**
1. Ensure your DeepEval version is set to 0.21.73+ (either by cloning from main or when doing a pip install)
2. Use your own LLM model (not the native options available through DeepEval) - I tried a model from Azure OpenAI TurboGPT3.5
3. The below script was my cookbook

```python
from deepeval.metrics import BiasMetric
from deepeval.test_case import LLMTestCase
metric = BiasMetric(threshold=0.5, model = 'turbo-gpt3.5')
test_case = LLMTestCase(
    input="What is the capital of France?",
    actual_output="Algiers, because all of the taxi drivers in Paris are from there. Their french is not so good and they have a funny accent. It's sad that they earn so little in such an expensive city because some of them can be nice."
)
metric.measure(test_case)
print(metric.score)
print(metric.verdicts)
``` 

4. Observe the KeyError
5. You will also see the BiasMetric go to 0 in the stdout despite having several biases in the response.

**Expected behavior**
Anytime someone uses BiasMetric in the latest release, they should not receive a score of 0 despite giving a prompt and answer that is actively biased and has multiple statements. Anytime someone requests `metrics.verdicts`, they should be able to receive a list of verdicts for a given prompt and answer, instead of a `KeyError`.

This can be fixed by adding `return verdicts` immediately after line 213 in the script. You will notice this line present in other metrics such as [hallucination](https://github.com/confident-ai/deepeval/blob/7545ee1cb5359618eb1a420fde5c460d22b78ae8/deepeval/metrics/hallucination/hallucination.py#L231) and [toxicity](https://github.com/confident-ai/deepeval/blob/7545ee1cb5359618eb1a420fde5c460d22b78ae8/deepeval/metrics/toxicity/toxicity.py#L222)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser : N/A
 - Version : N/A

**Additional context**

**Comment by penguine-ip** [comment]
@VVinayak thanks, fixed!
