### ISSUE TITLE
Tool Correctness documentation page shows using ContextualRelevancyMetric instead of ToolCorrectnessMetric 

### ISSUE THREAD

**Issue by vensr** [confident-ai/deepeval#940]
**Describe the bug**
Tool Correctness documentation page shows using ContextualRelevancyMetric instead of ToolCorrectnessMetric. The example is incorrect.

https://docs.confident-ai.com/docs/metrics-tool-correctness

**To Reproduce**
1. Go to 'https://docs.confident-ai.com/docs/metrics-tool-correctness'
2. Check the example

**Expected behavior**
The document needs to be correct to show the example to use ToolCorrectnessMetric
[Tool Correctness _ DeepEval - The Open-Source LLM Evaluation Framework.pdf](https://github.com/user-attachments/files/16557206/Tool.Correctness._.DeepEval.-.The.Open-Source.LLM.Evaluation.Framework.pdf)

**Comment by penguine-ip** [comment]
@vensr thanks!
