### ISSUE TITLE
Parameters mentioned in Conversation Relevancy Doc page is of Faithfulness

### ISSUE THREAD

**Issue by vensr** [confident-ai/deepeval#944]
**Describe the bug**
The parameters mentioned in the conversational doc page is incorrect. It mentions about Faithfulness parameters for Conversation Relevancy.

**To Reproduce**
1. Go to 'https://docs.confident-ai.com/docs/metrics-conversation-relevancy'
2. Check the parameters section.

**Expected behavior**
The document needs to be corrected to show the Conversation Relevancy parameters.
[Conversation Relevancy _ DeepEval - The Open-Source LLM Evaluation Framework.pdf](https://github.com/user-attachments/files/16558198/Conversation.Relevancy._.DeepEval.-.The.Open-Source.LLM.Evaluation.Framework.pdf)

**Comment by penguine-ip** [comment]
Hey @vensr thanks for bringing this up, do you mean this link? https://docs.confident-ai.com/docs/metrics-conversation-relevancy#required-arguments

**Comment by vensr** [comment]
Yes the same link.

**Comment by penguine-ip** [comment]
@vensr it is correct.
