### ISSUE TITLE
Error on dataset.pull: TypeError: Api.send_request() got an unexpected keyword argument 'params'

### ISSUE THREAD

**Issue by bendominguez0111** [confident-ai/deepeval#969]
dataset.pull does not work because it is sending a params keyword argument to Api.send_request() that does not exist. Checked the source code and it indeed does not look like that keyword argument is present.

**Screenshots**
![image](https://github.com/user-attachments/assets/9be535a9-ef3e-4225-ba6e-ed99acb7a19f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 22.04

**Comment by penguine-ip** [comment]
@bendominguez0111 thanks for bringing this up, fixed in latest release (v1.1.0), thanks!
