### ISSUE TITLE
About 'node' in prompt of contextual_precision

### ISSUE THREAD

**Issue by Ishiki-Iroha** [confident-ai/deepeval#976]
**❗BEFORE YOU BEGIN❗**
Are you on discord? 🤗 We'd love to have you asking questions on discord instead: https://discord.com/invite/a3K9c8GRGt

**Describe the bug**
I noticed that the contextual_precision prompt mentioned 'The retrieval contexts is a list of JSON with three keys: `verdict`, `reason` (reason for the verdict) and `node`. ' However, when I actually used the contextual_precision, I did not observe the generated prompt containing the 'node' key. Why is that?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by penguine-ip** [comment]
@Ishiki-Iroha Must be a bug we forgot to remove in the prompts, thanks for bringing it up!
